### PR TITLE
multi website test scopes

### PR DESCRIPTION
**Pull request by boehsermoe**
Test scope for multi website support #274

### CODE REVIEW

**Comment by nadar** [comment]
@boehsermoe so we could add this now?

**Comment by boehsermoe** [comment]
Required at first a cms version update, currently it use still v3.5.3.
Or use dev-master as requirement...

**Comment by nadar** [comment]
please add dev-master as requirement :+1:

**Comment by nadar** [comment]
going to tag this a version 3.0

**Pull request merged**
